# Generated by Django 3.1.5 on 2021-01-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210131_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='datedeleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
